version: '2'

services:
  blogapi:
    build:
      context: .
    image: blogapi
    ports:
      - ":8080:8080"
    volumes:
      - $PWD/blog.db:/app/blog.db
    #network_mode: host

volumes:
  db:
